language: node_js
node_js:
  - "8"

env:
  global:
    - NODE_ENV="test"

before_install:
  - npm install -g yarn nyc coveralls

script:
  - yarn test:coverage
  - nyc report --reporter=text-lcov | coveralls
